/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGUserInfoSettingConfig setUserInfoDict:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    obj = new ObjC.Object(args[2]);
    log(`-[KGUserInfoSettingConfig setUserInfoDict:${obj.toString()}]`);
  },

  onLeave(log, retval, state) {
  }
});
