/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGUserInfoSettingConfig userInfoDict].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`-[KGUserInfoSettingConfig userInfoDict]`);
  },

  onLeave(log, retval, state) {
    const dict = new ObjC.Object(retval);
    const enumerator = dict.keyEnumerator();
    let key;
    while ((key = enumerator.nextObject()) !== null) {
      const value = dict.objectForKey_(key);
      log(`${key} : ${value}`);
    }
    // log(`-[KGUserInfoSettingConfig userInfoDict]:${obj}`);
    // log(`-[KGUserInfoSettingConfig userInfoDict]:${retval.$className}`);
    // log(`-[KGUserInfoSettingConfig userInfoDict:${obj.toString()}]`);
  }
});


// userQuickTokenValue : {
//     679797010 = 14b459c87712e8c6d8147bf72e3c2a4a4cc2ad8af973df237039eda3b203392f;
// }
// UserHasModifiedQualityInWiFi : {
//     0 = 1;
// }
// UserHasModifiedQualityIn3G : {
//     0 = 1;
// }
// gdtSplashOrderPreLoaded : 1