/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeilhyvkw setQmei_lruy3x:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeilhyvkw setQmei_lruy3x:${args[2]}]`);
  },

  onLeave(log, retval, state) {
  }
});
