/*
 * Auto-generated by Frida. Please modify to match the signature of +[UICKeyChainStore dataForKey:service:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UICKeyChainStore dataForKey:${args[2]} service:${args[3]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    const objcObj2 = new ObjC.Object(args[3]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
