/*
 * Auto-generated by Frida. Please modify to match the signature of +[UICKeyChainStore keyChainStoreWithService:accessGroup:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UICKeyChainStore keyChainStoreWithService:${args[2]} accessGroup:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
