/*
 * Auto-generated by Frida. Please modify to match the signature of +[UICKeyChainStore setString:forKey:service:accessGroup:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UICKeyChainStore setString:${args[2]} forKey:${args[3]} service:${args[4]} accessGroup:${args[5]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    const objcObj2 = new ObjC.Object(args[3]);
    const objcObj3 = new ObjC.Object(args[4]);
    const objcObj4 = new ObjC.Object(args[5]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）'); 
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
    log('👉'+ objcObj3.toString() + '（' + objcObj3.$className + '）');
    log('👉'+ objcObj4.toString() + '（' + objcObj4.$className + '）');
  },
  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
