/*
 * Auto-generated by Frida. Please modify to match the signature of +[UICKeyChainStore setString:forKey:service:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UICKeyChainStore setString:${args[2]} forKey:${args[3]} service:${args[4]}]`);
    let objcObj1 = new ObjC.Object(args[2]);
    const objcObj2 = new ObjC.Object(args[3]);
    const objcObj3 = new ObjC.Object(args[4]);
    log('👉 ' + formatObjCObject(objcObj1));
    log('👉 ' + formatObjCObject(objcObj2));
    log('👉 ' + formatObjCObject(objcObj3));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj) + '\n');
  }
});
