/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeijxh qimeiServiceMap].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeijxh qimeiServiceMap]`);
  },

  onLeave(log, retval, state) {
  }
});
