/*
 * Auto-generated by Frida. Please modify to match the signature of -[NeeFileCache fileNameForKey:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`-[NeeFileCache fileNameForKey:${args[2]}]`);
    this.objcObj = new ObjC.Object(args[2]);
  },

  onLeave(log, retval, state) {
    const ret = new ObjC.Object(retval);
    log(`NeeFileCache fileNameForKey: ${this.objcObj.toString()} value: ${ret.toString()}`);
    // if (this.objcObj.toString().includes('appUdid')){
    //   log(`NeeFileCache key: ${this.objcObj.toString()} value: ${ret.toString()}`);
    //   log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    // }
  }
});
