/*
 * Auto-generated by Frida. Please modify to match the signature of -[NeeFileCache objectForKeyedSubscript:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    this.objcObj = new ObjC.Object(args[2]);
    // log(`-[NeeFileCache objectForKeyedSubscript:${objcObj.toString()}]`);
  },

  onLeave(log, retval, state) {
    const ret = new ObjC.Object(retval);
    log(`NeeFileCache key: ${this.objcObj.toString()} value: ${ret.toString()}(${ret.$className})`);//
    // if (this.objcObj.toString().includes('appUdid')){
    //   log(`NeeFileCache key: ${this.objcObj.toString()} value: ${ret.toString()}`);
    //   log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    // }
  }
});
