/*
 * Auto-generated by Frida. Please modify to match the signature of -[NeeFileCache setObject:forKey:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`-[NeeFileCache setObject:${args[2]} forKey:${args[3]}]`);
    const objcObj = new ObjC.Object(args[2]);
    const keyObj = new ObjC.Object(args[3]);
    log('👉key: ' + keyObj.toString() + ' value: ' + objcObj.toString());
    //如果 key == appUdid时才打印栈
    if (keyObj.toString().includes('appUdid')){
      log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    }
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈:' + objcObj.toString());
  }
});
