/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeitkcd qmei_mrsh8ba].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeitkcd qmei_mrsh8ba]`);
  },

  onLeave(log, retval, state) {
  }
});
