/*
 * Auto-generated by Frida. Please modify to match the signature of CFStringGetCStringPtr.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

// __handlers__/CFStringGetCStringPtr.js
defineHandler({
  onEnter(log, args, state) {
    // args[0] 是 CFStringRef
    // args[1] 是编码参数
    var cfString = args[0];
    var encoding = args[1];
    
    // 将 CFStringRef 转换为 JavaScript 字符串
    var stringContent = Memory.readUtf8String(cfString);
    
    log('CFStringGetCStringPtr()');
    log('字符串内容:2 ' + stringContent);
    log('编码: ' + encoding);
    log('指针地址: ' + cfString);
    
    // 检查是否包含 IDFA 相关关键词
    if (stringContent && (stringContent.includes('IDFA') || 
                         stringContent.includes('idfa') || 
                         stringContent.includes('advertising') ||
                         stringContent.length === 36)) {
        log('🚨 检测到可能的 IDFA 相关字符串!');
    }
  },

  onLeave(log, retval, state) {
    // log('返回值: ' + retval);
  }
});
