/*
 * Auto-generated by Frida. Please modify to match the signature of +[StatisticInfo udid].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {

  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log(`+[StatisticInfo udid]：` + objcObj.toString() + '（' + objcObj.$className + '）' + '\n');
    //+[StatisticInfo udid]：de200408f3f04354795413b01dd77c57d0967c51（__NSCFString）
  }
});
