/*
 * Auto-generated by Frida. Please modify to match the signature of +[Qmeixfln qmei_egw3v:andServiceName:accAttribute:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[Qmeixfln qmei_egw3v:${args[2]} andServiceName:${args[3]} accAttribute:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
