/*
 * Auto-generated by Frida. Please modify to match the signature of +[Qmeixfln qmei_xkk0xm5b:withAppKey:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[Qmeixfln qmei_xkk0xm5b:${args[2]} withAppKey:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
