/*
 * Auto-generated by Frida. Please modify to match the signature of +[Qmeixfln qmei_fozpsy3b:andServiceName:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[Qmeixfln qmei_fozpsy3b:${args[2]} andServiceName:${args[3]} error:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
