/*
 * Auto-generated by Frida. Please modify to match the signature of -[GDTTangramHostDeviceInfo qimei36].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`-[GDTTangramHostDeviceInfo qimei36]`);
    this.name = new ObjC.Object(args[0]).toString();
  },

  onLeave(log, retval, state) {
    var obj = new ObjC.Object(retval).toString();
    log(`-[GDTTangramHostDeviceInfo qimei36] = ${obj}`);

    // var p = ptr(retval);
    // try {
    //     var obj = new ObjC.Object(p);
    //     console.log('OC object:', obj.$className, obj.toString());
    // } catch (e) {
    //     console.log('not OC object');
    //     console.log('pointer value:', Memory.readPointer(p));
    // }
  }
});
