/*
 * Auto-generated by Frida. Please modify to match the signature of -[GDTTangramHostDeviceInfo ua].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[GDTTangramHostDeviceInfo ua]`);
  },

  onLeave(log, retval, state) {
    var obj = new ObjC.Object(retval).toString();
    log(`-[GDTTangramHostDeviceInfo ua] = ${obj}`);
  }
});
