/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm handlerPostUseTimeWithLocalTime:totalTime:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm handlerPostUseTimeWithLocalTime:${args[2]} totalTime:${args[3]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    let objcObj2 = ObjC.Object(args[3]);
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
  },

  onLeave(log, retval, state) {
    let objcObj = ObjC.Object(retval);
    log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
