/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_wpbssz4:isForce:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_wpbssz4:${args[2]} isForce:${args[3]}]`);
    const objcObj1 = new ObjC.Object(args[2]);
    log('👉 ' + formatObjCObject(objcObj1));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj) + '\n');
  }
});
