/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_qrlegk:serverCode:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_qrlegk:${args[2]} serverCode:${args[3]}]`);
    const objcObj1 = new ObjC.Object(args[2]);
    log('👉 ' + formatObjCObject(objcObj1));
    let objcObj2 = new ObjC.Object(args[3]);
    log('👉 ' + formatObjCObject(objcObj2));
    log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj) + '\n');
  }
});
