/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_wqtq9f].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_wqtq9f]`);
    // if (!args[2].isNull()) {
    //   const objcObj1 = new ObjC.Object(args[2]);
    //   log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    // } else {
    //   log('👉 arg0 is nil');
    // }
  },

  onLeave(log, retval, state) { 
    // if (retval.isNull()) {
    //   log('👈: retval is nil\n');
    //   return;
    // }
    // const objcObj = new ObjC.Object(retval);
    // log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
