/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_qrlegk:serverCode:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_qrlegk:${args[2]} serverCode:${args[3]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    let objcObj2 = ObjC.Object(args[3]);
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
    log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    let objcObj = new ObjC.Object(retval);
    log('👈: ' + objcObj.toString() + '（' + objcObj.$className + '）' + '\n');
  }
});
