/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_e948ze8:code:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_e948ze8:${args[2]} code:${args[3]}]`);
    objcObj1 = new ObjC.Object(args[2]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    objcObj2 = new ObjC.Object(args[3]);
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
  },

  onLeave(log, retval, state) {
    objcObj = new ObjC.Object(retval);
    log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
