/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_fgcupvyp:oldQ36:newQ16:newQ36:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_fgcupvyp:${args[2]} oldQ36:${args[3]} newQ16:${args[4]} newQ36:${args[5]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    let objcObj2 = ObjC.Object(args[3]);
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
    let objcObj3 = ObjC.Object(args[4]);
    log('👉'+ objcObj3.toString() + '（' + objcObj3.$className + '）');
    let objcObj4 = ObjC.Object(args[5]);
    log('👉'+ objcObj4.toString() + '（' + objcObj4.$className + '）');
  },

  onLeave(log, retval, state) {
    let objcObj = new ObjC.Object(retval);
    log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
