/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_fgcupvyp:oldQ36:newQ16:newQ36:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_fgcupvyp:${args[2]} oldQ36:${args[3]} newQ16:${args[4]} newQ36:${args[5]}]`);
    let objcObj1 = new ObjC.Object(args[2]);
    log('👉 ' + formatObjCObject(objcObj1));
    let objcObj2 = new ObjC.Object(args[3]);
    log('👉 ' + formatObjCObject(objcObj2));
    let objcObj3 = new ObjC.Object(args[4]);
    log('👉 ' + formatObjCObject(objcObj3));
    let objcObj4 = new ObjC.Object(args[5]);
    log('👉 ' + formatObjCObject(objcObj4));
  },

  onLeave(log, retval, state) {
    let objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj) + '\n');
  }
});
