/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeiegtm qmei_tc50i0:newQimei:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeiegtm qmei_tc50i0:${args[2]} newQimei:${args[3]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    let objcObj2 = ObjC.Object(args[3]);
    log('👉' + objcObj1.toString() + '（' + objcObj1.$className + '）');
    log('👉' + objcObj2.toString() + '（' + objcObj2.$className + '）');
    log('stack: ' + Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    let objcObj = ObjC.Object(retval);
    log('👈: ' + objcObj.$className + ' ' + objcObj.toString() + '\n');
  }
});