/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGTencentStatistics forceRereshDeviceIDMachineName:o36:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[KGTencentStatistics forceRereshDeviceIDMachineName:${args[2]} o36:${args[3]}]`);
    const objcObj1 = new ObjC.Object(args[2]);
    const objcObj2 = new ObjC.Object(args[3]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈: ' + objcObj.toString() + '（' + objcObj.$className + '）' + '\n');
  }
});
