/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGTencentStatistics q36].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */
// frida-trace -U -f com.kugou.kugou1002 -m "-[KGTencentStatistics q36]" -i "CC_MD5"
defineHandler({
  onEnter(log, args, state) {
    // log(`-[KGTencentStatistics q36]`);
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    // log(`-[KGTencentStatistics q36] retval: ${objcObj.toString()}`);

    // 获取原始返回值
    // if (!retval.isNull()) {
    //   const objcObj = new ObjC.Object(retval);
    //   log(`👈 [KGTencentStatistics q36] 原始返回值: ${objcObj.toString()} (${objcObj.$className})`);
    // } else {
    //   log(`👈 [KGTencentStatistics q36] 原始返回值: nil`);
    // }
    
    // 修改返回值
    const newValue = "1482ec024f1effab71edd705000016319900";
    const newString = ObjC.classes.NSString.stringWithString_(newValue);
    retval.replace(ptr(newString));
    
    log(`✅ -[KGTencentStatistics q36] ${objcObj.toString()} -> ${newValue}\n`);
  }
});
