/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGTencentStatistics reportByTencentDaTong:event:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[KGTencentStatistics reportByTencentDaTong:${args[2]} event:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
