/*
 * Auto-generated by Frida. Please modify to match the signature of -[OstarService isValidOstar16:ostar36:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[OstarService isValidOstar16:${args[2]} ostar36:${args[3]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    let objcObj2 = ObjC.Object(args[3]);
    log('👉'+ objcObj2.toString() + '（' + objcObj2.$className + '）');
  },

  onLeave(log, retval, state) {
    let objcObj = ObjC.Object(retval);
    log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
