/*
 * Auto-generated by Frida. Please modify to match the signature of -[OstarService isValidOstar16:ostar36:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[OstarService isValidOstar16:${args[2]} ostar36:${args[3]}]`);
    let objcObj1 = new ObjC.Object(args[2]);
    log('👉 ' + formatObjCObject(objcObj1));
    let objcObj2 = new ObjC.Object(args[3]);
    log('👉 ' + formatObjCObject(objcObj2));
  },

  onLeave(log, retval, state) {
    let objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj) + '\n');
  }
});
