/*
 * Auto-generated by Frida. Please modify to match the signature of -[OstarService setAppkey:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[OstarService setAppkey:${args[2]}]`);
    const objcObj = new ObjC.Object(args[2]);
    log('👉类型: ' + objcObj.$className  + ' 值: ' + objcObj.toString());
    // log('调用栈: ' + Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log(`👈: ${objcObj.$className +" "+ objcObj.toString()}`);
  }
});
