/*
 * Auto-generated by Frida. Please modify to match the signature of -[OstarService setUserId:forType:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[OstarService setUserId:${args[2]} forType:${args[3]}]`);
    let objcObj1 = new ObjC.Object(args[2]);
    const objcObj2 = new ObjC.Object(args[3]);
    log('👉类型: ' + objcObj1.$className  + ' 值: ' + objcObj1.toString());
    log('👉类型: ' + objcObj2.$className  + ' 值: ' + objcObj2.toString());
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log(`👈: ${objcObj.$className +" "+ objcObj.toString()}`);
  }
});
