/*
 * Auto-generated by Frida. Please modify to match the signature of -[OstarService startWithO16:o36:delegate:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */// 根据类型格式化输出 Objective-C 对象
function formatObjCObject(objcObj) {
  if (!objcObj || objcObj.isNull()) {
    return 'nil';
  }
  
  const className = objcObj.$className;
  let output = '';
  
  try {
    // NSString 类型
    if (className === 'NSString' || className === '__NSCFString' || className === '__NSCFConstantString' || className === 'NSMutableString') {
      output = objcObj.toString();
    }
    // NSData 类型
    else if (className === 'NSData' || className === '__NSCFData' || className === 'NSMutableData') {
      const dataLength = objcObj.length();
      const dataBytes = objcObj.bytes();
      
      // 尝试 UTF-8 字符串
      try {
        const utf8String = Memory.readUtf8(dataBytes, Math.min(dataLength, 256));
        const isPrintable = /^[\x20-\x7E\s]*$/.test(utf8String);
        if (isPrintable && utf8String.length > 0 && dataLength <= 256) {
          output = `UTF-8: ${utf8String}`;
        } else {
          // 显示十六进制
          const hexString = Memory.readByteArray(dataBytes, Math.min(dataLength, 64))
            .map(b => ('0' + (b & 0xFF).toString(16)).slice(-2))
            .join(' ');
          output = dataLength <= 64 ? `Hex: ${hexString}` : `Hex (first 64 bytes): ${hexString}... (total: ${dataLength})`;
        }
      } catch (e) {
        // UTF-8 失败，显示十六进制
        const hexString = Memory.readByteArray(dataBytes, Math.min(dataLength, 64))
          .map(b => ('0' + (b & 0xFF).toString(16)).slice(-2))
          .join(' ');
        output = dataLength <= 64 ? `Hex: ${hexString}` : `Hex (first 64 bytes): ${hexString}... (total: ${dataLength})`;
      }
    }
    // NSNumber 类型
    else if (className === 'NSNumber' || className === '__NSCFNumber') {
      output = objcObj.toString();
    }
    // NSDictionary 类型
    else if (className === 'NSDictionary' || className === '__NSCFDictionary' || className === 'NSMutableDictionary') {
      output = objcObj.toString();
    }
    // NSArray 类型
    else if (className === 'NSArray' || className === '__NSCFArray' || className === 'NSMutableArray') {
      const count = objcObj.count();
      output = `Array[${count}]: ${objcObj.toString()}`;
    }
    // Block 类型
    else if (className === '__NSStackBlock__' || className === '__NSMallocBlock__' || className === '__NSGlobalBlock__') {
      output = objcObj.toString();
    }
    // 其他类型，使用 toString()
    else {
      output = objcObj.toString();
    }
  } catch (e) {
    output = `[Error: ${e}] ${objcObj.toString()}`;
  }
  
  return `${output} (${className})`;
}



defineHandler({
  onEnter(log, args, state) {
    log(`-[OstarService startWithO16:${args[2]} o36:${args[3]} delegate:${args[4]}]`);
    let objcObj1 = new ObjC.Object(args[2]);
    const objcObj2 = new ObjC.Object(args[3]);
    const objcObj3 = new ObjC.Object(args[4]);
    log('👉 ' + formatObjCObject(objcObj1));
    log('👉 ' + formatObjCObject(objcObj2));
    log('👉 ' + formatObjCObject(objcObj3));
    //调用栈
    log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈: ' + objcObj.toString() + '（' + objcObj.$className + '）' + '\n');
  }
});
