/*
 * Auto-generated by Frida. Please modify to match the signature of -[OstarService startWithO16:o36:delegate:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[OstarService startWithO16:${args[2]} o36:${args[3]} delegate:${args[4]}]`);
    let objcObj1 = new ObjC.Object(args[2]);
    const objcObj2 = new ObjC.Object(args[3]);
    const objcObj3 = new ObjC.Object(args[4]);
    log('👉 ' + formatObjCObject(objcObj1));
    log('👉 ' + formatObjCObject(objcObj2));
    log('👉 ' + formatObjCObject(objcObj3));
    //调用栈
    log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈: ' + objcObj.toString() + '（' + objcObj.$className + '）' + '\n');
  }
});
