/*
 * Auto-generated by Frida. Please modify to match the signature of -[OstarService updateO16:o36:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[OstarService updateO16:${args[2]} o36:${args[3]}]`);
    log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈: ' + objcObj.toString() + '（' + objcObj.$className + '）' + '\n');
  }
});
