/*
 * Auto-generated by Frida. Please modify to match the signature of -[TDMQimeiService qimeiContentWithSetting:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[TDMQimeiService qimeiContentWithSetting:${args[2]}]`);
  },

  onLeave(log, retval, state) {
    log(`👈: ${retval}`);
  }
});
