/*
 * Auto-generated by Frida. Please modify to match the signature of +[GDTTangramDeviceManager getHostDeviceInfo].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`+[GDTTangramDeviceManager getHostDeviceInfo]`);
  },

  onLeave(log, retval, state) {
    // obj = readStdString(retval);
    var obj = new ObjC.Object(ptr(retval));
    log(`-[GDTTangramDeviceManager getHostDeviceInfo] = ${obj}`);

    var p = ptr(retval);
    try {
        var obj = new ObjC.Object(p);
        console.log('OC object:', obj.$className, obj.toString());
    } catch (e) {
        console.log('not OC object');
        console.log('pointer value:', Memory.readPointer(p));
    }
  }
});


 function readStdString(strPtr) {
  const bufPtr = strPtr;
  const size = Memory.readU64(strPtr.add(0x10));

  if (size <= 15) {
      return Memory.readUtf8String(bufPtr, size);
  } else {
      const realPtr = Memory.readPointer(bufPtr);
      return Memory.readUtf8String(realPtr, size);
  }
}