/*
 * Auto-generated by Frida. Please modify to match the signature of +[GDTTangramDeviceManager getTangramDeviceInfoWithScene:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`+[GDTTangramDeviceManager getTangramDeviceInfoWithScene:${args[2]}]`);
    this.objcObj = new ObjC.Object(args[2]);
  },

  onLeave(log, retval, state) {
    log(`-[GDTTangramDeviceManager getTangramDeviceInfoWithScene:]:${retval}`);
    // const dict = new ObjC.Object(retval);
    // const enumerator = dict.keyEnumerator();
    // let key;
    // while ((key = enumerator.nextObject()) !== null) {
    //   const value = dict.objectForKey_(key);
    //   log(`${key} : ${value}`);
    // }

    log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    // log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  }
});
