/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL apmStartWithType:and3rdType:andRegister:isSwitchAccount:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL apmStartWithType:${args[2]} and3rdType:${args[3]} andRegister:${args[4]} isSwitchAccount:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
