/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL bindingEmailWithUserId:email:password:successCallback:andErrorCallback:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL bindingEmailWithUserId:${args[2]} email:${args[3]} password:${args[4]} successCallback:${args[5]} andErrorCallback:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
