/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL changeBindindPhoneNumWithUserId:userToken:oldNum:num:oldCode:code:successCallback:andErrorCallback:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL changeBindindPhoneNumWithUserId:${args[2]} userToken:${args[3]} oldNum:${args[4]} num:${args[5]} oldCode:${args[6]} code:${args[7]} successCallback:${args[8]} andErrorCallback:${args[9]}]`);
  },

  onLeave(log, retval, state) {
  }
});
