/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL checkMobileVerifyCode:withPhoneNume:withBussinessType:AndRep:AndException:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL checkMobileVerifyCode:${args[2]} withPhoneNume:${args[3]} withBussinessType:${args[4]} AndRep:${args[5]} AndException:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
