/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL checkMobileVerifyCode:withBussinessType:AndRep:AndException:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL checkMobileVerifyCode:${args[2]} withBussinessType:${args[3]} AndRep:${args[4]} AndException:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
