/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL getBindInfoWithPhone:code:accessToken:accessId:accessKey:accCooperator:businessid:query:successCallback:andErrorCallback:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL getBindInfoWithPhone:${args[2]} code:${args[3]} accessToken:${args[4]} accessId:${args[5]} accessKey:${args[6]} accCooperator:${args[7]} businessid:${args[8]} query:${args[9]} successCallback:${args[10]} andErrorCallback:${args[11]}]`);
  },

  onLeave(log, retval, state) {
  }
});
