/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL getMobileQuickLoginPhoneNumWithTimeout:checkAheadFinsih:completeBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL getMobileQuickLoginPhoneNumWithTimeout:${args[2]} checkAheadFinsih:${args[3]} completeBlock:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
