/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL getMobileQuickLoginAuthorizationWithSecurityPhoneNum:isUseCache:completed:fromLogin:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL getMobileQuickLoginAuthorizationWithSecurityPhoneNum:${args[2]} isUseCache:${args[3]} completed:${args[4]} fromLogin:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
