/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL getSlidVerifyCodeAndPictureCodeImageWithType:codeType:andSuccessBlock:andException:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL getSlidVerifyCodeAndPictureCodeImageWithType:${args[2]} codeType:${args[3]} andSuccessBlock:${args[4]} andException:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
