/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL getThirdPartyAuthenticationInfo:andReturnUserInfo:andTargetVC:complection:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL getThirdPartyAuthenticationInfo:${args[2]} andReturnUserInfo:${args[3]} andTargetVC:${args[4]} complection:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
