/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL getUserGradeInfo:type:totalListenSec:superadditionSec:andRepBlock:andExpBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL getUserGradeInfo:${args[2]} type:${args[3]} totalListenSec:${args[4]} superadditionSec:${args[5]} andRepBlock:${args[6]} andExpBlock:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
