/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL getVerificationCodeImgeWithType:andSuccessBlock:andException:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL getVerificationCodeImgeWithType:${args[2]} andSuccessBlock:${args[3]} andException:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
