/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL headImageUploadApmWithError:andIndex:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL headImageUploadApmWithError:${args[2]} andIndex:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
