/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginThrowExceptionWithUserName:AndPassword:AndIsAutoLogin:AndIsSave:AndVerifyCode:AndVerifyKey:andMobile:andCode:andPartnerid:andOpenId:andAccessToken:andIsForceBindPhone:AndFromSource:andCheckCalmAccount:isSwitchAccount:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginThrowExceptionWithUserName:${args[2]} AndPassword:${args[3]} AndIsAutoLogin:${args[4]} AndIsSave:${args[5]} AndVerifyCode:${args[6]} AndVerifyKey:${args[7]} andMobile:${args[8]} andCode:${args[9]} andPartnerid:${args[10]} andOpenId:${args[11]} andAccessToken:${args[12]} andIsForceBindPhone:${args[13]} AndFromSource:${args[14]} andCheckCalmAccount:${args[15]} isSwitchAccount:${args[16]} AndError:${args[17]}]`);
  },

  onLeave(log, retval, state) {
  }
});
