/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginThrowExceptionWithUserName:AndPassword:AndUserid:AndIsAutoLogin:AndIsSave:AndVerifyCode:AndVerifyKey:andMobile:andCode:andPartnerid:andOpenId:andAccessToken:andIsForceBindPhone:AndFromSource:andCheckCalmAccount:isSwitchAccount:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginThrowExceptionWithUserName:${args[2]} AndPassword:${args[3]} AndUserid:${args[4]} AndIsAutoLogin:${args[5]} AndIsSave:${args[6]} AndVerifyCode:${args[7]} AndVerifyKey:${args[8]} andMobile:${args[9]} andCode:${args[10]} andPartnerid:${args[11]} andOpenId:${args[12]} andAccessToken:${args[13]} andIsForceBindPhone:${args[14]} AndFromSource:${args[15]} andCheckCalmAccount:${args[16]} isSwitchAccount:${args[17]} AndError:${args[18]}]`);
  },

  onLeave(log, retval, state) {
  }
});
