/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginWithUid:andQuickToken:t1:loginType:isNeedLogout:andError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginWithUid:${args[2]} andQuickToken:${args[3]} t1:${args[4]} loginType:${args[5]} isNeedLogout:${args[6]} andError:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
