/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginWithMobile:verifyCode:userId:password:businessid:toVerify:fromSource:checkCalmAccount:switchAccount:forceLogin:AndRep:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginWithMobile:${args[2]} verifyCode:${args[3]} userId:${args[4]} password:${args[5]} businessid:${args[6]} toVerify:${args[7]} fromSource:${args[8]} checkCalmAccount:${args[9]} switchAccount:${args[10]} forceLogin:${args[11]} AndRep:${args[12]} AndError:${args[13]}]`);
  },

  onLeave(log, retval, state) {
  }
});
