/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginWithMobile:verifyCode:userId:password:businessid:toVerify:isRegister:fromSource:checkCalmAccount:switchAccount:reqUserInfo:forceLogin:AndRep:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginWithMobile:${args[2]} verifyCode:${args[3]} userId:${args[4]} password:${args[5]} businessid:${args[6]} toVerify:${args[7]} isRegister:${args[8]} fromSource:${args[9]} checkCalmAccount:${args[10]} switchAccount:${args[11]} reqUserInfo:${args[12]} forceLogin:${args[13]} AndRep:${args[14]} AndError:${args[15]}]`);
  },

  onLeave(log, retval, state) {
  }
});
