/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginFromAppleID:identitytoken:authorizationCode:nickName:fromSource:forceLogin:checkCalmAccount:switchAccount:rep:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginFromAppleID:${args[2]} identitytoken:${args[3]} authorizationCode:${args[4]} nickName:${args[5]} fromSource:${args[6]} forceLogin:${args[7]} checkCalmAccount:${args[8]} switchAccount:${args[9]} rep:${args[10]} AndError:${args[11]}]`);
  },

  onLeave(log, retval, state) {
  }
});
