/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginTokenRenewalWithUid:AndToken:t1:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginTokenRenewalWithUid:${args[2]} AndToken:${args[3]} t1:${args[4]} AndError:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
