/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginWithOpenID:AndAccessToken:AndPartneid:AndExpDate:AndUnionid:loginRep:AndFromSource:toVerify:verifyUserId:forceLogin:checkCalmAccount:switchAccount:AndRep:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginWithOpenID:${args[2]} AndAccessToken:${args[3]} AndPartneid:${args[4]} AndExpDate:${args[5]} AndUnionid:${args[6]} loginRep:${args[7]} AndFromSource:${args[8]} toVerify:${args[9]} verifyUserId:${args[10]} forceLogin:${args[11]} checkCalmAccount:${args[12]} switchAccount:${args[13]} AndRep:${args[14]} AndError:${args[15]}]`);
  },

  onLeave(log, retval, state) {
  }
});
