/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL loginWithOpenID:AndAccessToken:AndPartneid:AndExpDate:AndUnionid:AndFromSource:toVerify:verifyUserId:forceLogin:checkCalmAccount:switchAccount:AndRep:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL loginWithOpenID:${args[2]} AndAccessToken:${args[3]} AndPartneid:${args[4]} AndExpDate:${args[5]} AndUnionid:${args[6]} AndFromSource:${args[7]} toVerify:${args[8]} verifyUserId:${args[9]} forceLogin:${args[10]} checkCalmAccount:${args[11]} switchAccount:${args[12]} AndRep:${args[13]} AndError:${args[14]}]`);
  },

  onLeave(log, retval, state) {
  }
});
