/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL quickLoginWithMobile:accessToken:accessId:accessKey:accCooperator:userId:isRegist:reqUserInfo:fromSource:checkCalmAccount:switchAccount:forceLogin:AndRep:AndError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL quickLoginWithMobile:${args[2]} accessToken:${args[3]} accessId:${args[4]} accessKey:${args[5]} accCooperator:${args[6]} userId:${args[7]} isRegist:${args[8]} reqUserInfo:${args[9]} fromSource:${args[10]} checkCalmAccount:${args[11]} switchAccount:${args[12]} forceLogin:${args[13]} AndRep:${args[14]} AndError:${args[15]}]`);
  },

  onLeave(log, retval, state) {
  }
});
