/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL quickTokenLoginWith:userToken:loginType:andSource:complete:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL quickTokenLoginWith:${args[2]} userToken:${args[3]} loginType:${args[4]} andSource:${args[5]} complete:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
