/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL refreshVIPInfoRetry:isSendException:infoHasChangedRep:noChangedRep:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL refreshVIPInfoRetry:${args[2]} isSendException:${args[3]} infoHasChangedRep:${args[4]} noChangedRep:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
