/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL refreshBookVipInfoIsNeedRetry:infoHasChangedRep:noChangedRep:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL refreshBookVipInfoIsNeedRetry:${args[2]} infoHasChangedRep:${args[3]} noChangedRep:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
