/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL registWithPhone:AndNickName:AndPassword:AndPhoto:AndCaptcha:AndSex:AndFromSource:AndForceReg:AndHeader:AndRep:AndException:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL registWithPhone:${args[2]} AndNickName:${args[3]} AndPassword:${args[4]} AndPhoto:${args[5]} AndCaptcha:${args[6]} AndSex:${args[7]} AndFromSource:${args[8]} AndForceReg:${args[9]} AndHeader:${args[10]} AndRep:${args[11]} AndException:${args[12]}]`);
  },

  onLeave(log, retval, state) {
  }
});
