/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL registWithUserWithUsername:AndNickName:AndPassword:AndEmail:AndSex:AndRep:AndException:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL registWithUserWithUsername:${args[2]} AndNickName:${args[3]} AndPassword:${args[4]} AndEmail:${args[5]} AndSex:${args[6]} AndRep:${args[7]} AndException:${args[8]}]`);
  },

  onLeave(log, retval, state) {
  }
});
