/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL registWithBirthDay:nickName:andSex:birthStr:photo:isThird:complectionBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL registWithBirthDay:${args[2]} nickName:${args[3]} andSex:${args[4]} birthStr:${args[5]} photo:${args[6]} isThird:${args[7]} complectionBlock:${args[8]}]`);
  },

  onLeave(log, retval, state) {
  }
});
