/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL retrievePasswordV2WithUser:getPwdType:verifyCode:verifyKey:successCallback:andErrorCallback:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL retrievePasswordV2WithUser:${args[2]} getPwdType:${args[3]} verifyCode:${args[4]} verifyKey:${args[5]} successCallback:${args[6]} andErrorCallback:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
