/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL sendUpdateLoginEmaiWithUserId:successCallback:andErrorCallback:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL sendUpdateLoginEmaiWithUserId:${args[2]} successCallback:${args[3]} andErrorCallback:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
