/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL sendOldEmaiWithUserId:userToken:successCallback:andErrorCallback:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL sendOldEmaiWithUserId:${args[2]} userToken:${args[3]} successCallback:${args[4]} andErrorCallback:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
