/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL sendRenewalLoginSuccessNotifie:andUserName:dic:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL sendRenewalLoginSuccessNotifie:${args[2]} andUserName:${args[3]} dic:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
