/*
 * Auto-generated by Frida. Please modify to match the signature of +[UserOpBLL showCalmAlerForDeletedAccount:complete:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[UserOpBLL showCalmAlerForDeletedAccount:${args[2]} complete:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
