/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL unbindOtherAccountWithAccountType:phoneNum:code:andRepBlock:andExpBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL unbindOtherAccountWithAccountType:${args[2]} phoneNum:${args[3]} code:${args[4]} andRepBlock:${args[5]} andExpBlock:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
