/*
 * Auto-generated by Frida. Please modify to match the signature of -[UserOpBLL updateUserInfoWithThirdPart:andHeadImageUrl:andSex:andFinishCallback:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UserOpBLL updateUserInfoWithThirdPart:${args[2]} andHeadImageUrl:${args[3]} andSex:${args[4]} andFinishCallback:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
