/*
 * Auto-generated by Frida. Please modify to match the signature of +[KQUserOpBLL userID].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`+[KQUserOpBLL userID]`);
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('-[KQUserOpBLL userID]:'+ objcObj.toString() + '（' + objcObj.$className + '）');
    // log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  }
});
