/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGDeviceFPManager getDeviceFingerprintID].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[KGDeviceFPManager getDeviceFingerprintID]`);
    const objcObj = new ObjC.Object(args[2]);
    log('👉'+ objcObj.toString() + '（' + objcObj.$className + '）');

    // const strObj = new ObjC.Object(ptr("0x11331B4F0"));
    // log('👉 ObjC: ' + strObj.toString() + '（' + strObj.$className + '）');
    //调用栈
    // log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈: ' + objcObj.toString() + '（' + objcObj.$className + '）' + '\n');
  }
});
