/*
 * Auto-generated by Frida. Please modify to match the signature of CC_MD5.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */
// frida-trace -U -f com.kugou.kugou1002 -m "-[KGTencentStatistics q36]" -i "CC_MD5"
// frida-trace -D fa6f4e5a190858ab2441952057f189eb5c15b595 -f com.kugou.kugou1002 -m "-[KGTencentStatistics q36]" -i "CC_MD5"   
defineHandler({
  onEnter: function (log, args, state) {
    this.args0 = args[0];
    this.args2 = args[2];
    
    // 读取输入字符串并检查是否包含 "q36"
    try {
      var inputStr = this.args0.readUtf8String();
      if (inputStr && inputStr.indexOf('q36') !== -1) {
        // 只在包含 q36 时才保存堆栈信息
        this.shouldLogBacktrace = true;
        this.backtrace = 'called：\n' + Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n';
      } else {
        this.shouldLogBacktrace = false;
      }
    } catch (e) {
      this.shouldLogBacktrace = false;
    }
  },

  onLeave: function (log, retval, state) {
    var ByteArray = Memory.readByteArray(this.args2, 16);
    var uint8Array = new Uint8Array(ByteArray);
 
    var str = "";
    for (var i = 0; i < uint8Array.length; i++) {
        var hextemp = (uint8Array[i].toString(16))
        if (hextemp.length == 1){
            hextemp = "0" + hextemp
        }
        str += hextemp;
    }
    
    // 只在包含 q36 时才打印堆栈
    // if (this.shouldLogBacktrace && this.backtrace) {
      log(`CC_MD5：${this.args0.readUtf8String()}`);
      log(`CC_MD5：${str}`);
    //   log(this.backtrace);
    // }
  }
});


