/*
 * Auto-generated by Frida. Please modify to match the signature of +[AppsFlyerUtils isJailbrokenWithSkipAdvancedJailbreakValidation:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[AppsFlyerUtils isJailbrokenWithSkipAdvancedJailbreakValidation:${args[2]}]`);
    let objcObj = ObjC.Object(args[2]);
    log('👉'+ objcObj.toString() + '（' + objcObj.$className + '）');
  },

  onLeave(log, retval, state) {
    log("retval: " + retval + " " + typeof retval);
    // try {
    //   let obj = new ObjC.Object(retval);
    //   console.log("retval Obj:", obj.toString());
    //   console.log("JSON:", obj.toJSON ? obj.toJSON() : "no toJSON");
    // } catch (e) {
    //   console.log("Not an ObjC object, raw ptr:", retval);
    // }
    // let objcObj = ObjC.Object(retval);
    // log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});
