/*
 * Auto-generated by Frida. Please modify to match the signature of +[AlbumShowBLL saveAlbumShowInfoCache:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[AlbumShowBLL saveAlbumShowInfoCache:${args[2]}]`);
    const objcObj = new ObjC.Object(args[2]);
    log('👉value: ' + objcObj.toString());
    // log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
  }
});
