/*
 * Auto-generated by Frida. Please modify to match the signature of -[TDMQimeiHandler isRequestingQimei].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[TDMQimeiHandler isRequestingQimei]`);
    const objcObj = new ObjC.Object(args[2]);
    log('👉 ' + formatObjCObject(objcObj) + '\n');
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj));
  }
});
