/*
 * Auto-generated by Frida. Please modify to match the signature of -[TDMQimeiHandler isRequestingQimei].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[TDMQimeiHandler isRequestingQimei]`);
  },

  onLeave(log, retval, state) {
    log(`👈: ${retval}`);
  }
});
