/*
 * Auto-generated by Frida. Please modify to match the signature of -[TDMQimeiHandler postQimeiChangeWithOldQ16:oldQ36:newQ16:newQ36:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[TDMQimeiHandler postQimeiChangeWithOldQ16:${args[2]} oldQ36:${args[3]} newQ16:${args[4]} newQ36:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
