/*
 * Auto-generated by Frida. Please modify to match the signature of -[TDMQimeiHandler updateQimeiAndCallBackWithQimeiJson:serverCode:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[TDMQimeiHandler updateQimeiAndCallBackWithQimeiJson:${args[2]} serverCode:${args[3]}]`);
    const objcObj1 = new ObjC.Object(args[2]);
    log('👉 ' + formatObjCObject(objcObj1));
    const objcObj2 = new ObjC.Object(args[3]);
    log('👉 ' + formatObjCObject(objcObj2));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj));
  }
});
