/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGDeviceFPHttpDao requestDeviceDFIDWith:isSmallPackage:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[KGDeviceFPHttpDao requestDeviceDFIDWith:${args[2]} isSmallPackage:${args[3]} error:${args[4]}]`);
    var obj = new ObjC.Object(args[2]);
    log('args[2] OC object:', obj.$className, obj.toString());
    log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n')+ '\n');
  },

  onLeave(log, retval, state) {
    var p = ptr(retval);
    try {
        var obj = new ObjC.Object(p);
        log('retval OC object:', obj.$className, obj.toString());
    } catch (e) {
        log('retval not OC object');
        log('retval pointer value:', Memory.readPointer(p));
    }
  }
});


/*

 10865 ms  -[KGDeviceFPHttpDao requestDeviceDFIDWith:0x283c7b570 isSmallPackage:0x1 error:0x16df9e898]
 10865 ms  args[2] OC object: __NSCFString 118017223436835596 //固定的
 10936 ms  retval OC object: __NSDictionaryM {
    dfid = 0Q42Ir00ifEl061bVi2XPpDB;//动态变化的
    scheme = 0;
}

*/