/*
 * Auto-generated by Frida. Please modify to match the signature of -[RDConfigStorage asyncLoadDiskWithGuid:env:completedBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[RDConfigStorage asyncLoadDiskWithGuid:${args[2]} env:${args[3]} completedBlock:${args[4]}]`);
    // log("👉 guid -> " + Object(args[2]).toString());
    // log("👉 env -> " + Object(args[3]).toString());
    log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
  }
});
