/*
 * Auto-generated by Frida. Please modify to match the signature of -[QimeiContent setQimeiNew:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[QimeiContent setQimeiNew:${args[2]}]`);
    let objcObj = ObjC.Object(args[2]);
    log('👉类型: ' + objcObj.$className  + ' 值: ' + objcObj.toString());
    log('调用栈: ' + Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    log(`👈: ${retval}`);
  }
});
