/*
 * Auto-generated by Frida. Please modify to match the signature of -[QimeiContent setQimeiNew:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[QimeiContent setQimeiNew:${args[2]}]`);
    const objcObj = new ObjC.Object(args[2]);
    log('👉 ' + formatObjCObject(objcObj));
    // log('调用栈: ' + Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('👈 ' + formatObjCObject(objcObj));
  }
});
