/*
 * Auto-generated by Frida. Please modify to match the signature of -[ZBHWindowWindowTag appVersion].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`-[ZBHWindowWindowTag appVersion]`);
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('-[ZBHWindowWindowTag appVersion]:'+ objcObj.toString() + '（' + objcObj.$className + '）');
  }
});
