/*
 * Auto-generated by Frida. Please modify to match the signature of -[ZBHWindowWindowTag deviceID].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // log(`-[ZBHWindowWindowTag deviceID]`);
    log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log('-[ZBHWindowWindowTag deviceID]:'+ objcObj.toString() + '（' + objcObj.$className + '）');
  }
});
