/*
 * Auto-generated by Frida. Please modify to match the signature of -[ZBHWindowWindowTag setUid:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    const objcObj = new ObjC.Object(args[2]);
    log(`-[ZBHWindowWindowTag setUid:${objcObj.toString()}]`);
    log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
  }
});

//   3813 ms  -[ZBHWindowWindowTag setUid:11ca09173e0e2c6121e2f5a55354fa88888]
//   3813 ms  0x10d2ba848 kugou!0xcd96848 (0x10cd96848)
// 0x1ca6027c8 libdispatch.dylib!_dispatch_client_callout
// 0x1ca5d2f40 libdispatch.dylib!_dispatch_once_callout
// 0x10d2ba7ec kugou!0xcd967ec (0x10cd967ec)
// 0x1072a9d80 kugou!0x6d85d80 (0x106d85d80)
// 0x1ca6027c8 libdispatch.dylib!_dispatch_client_callout
// 0x1ca5d2f40 libdispatch.dylib!_dispatch_once_callout
// 0x1072a9c70 kugou!-[KGMusicToolyManager forceSetUpToolyWithUserId:deviceId:force:]
// 0x1072a9ae8 kugou!-[KGMusicToolyManager setUpTooly]
// 0x109499ecc kugou!-[KGToolyTask afterStartInit]
// 0x10923df20 kugou!-[KGStartUpTaskManager pTaskObjectperform:queueKey:]
// 0x10923cd00 kugou!0x8d18d00 (0x108d18d00)
// 0x10923b698 kugou!-[KGStartUpTaskSysQueue runTasks:]
// 0x10923dbd8 kugou!-[KGStartUpTaskManager pRunQueueWithTasks:queueKey:]
// 0x10923c37c kugou!-[KGStartUpTaskManager pRunWithQueueKey:]
// 0x1065539cc kugou!-[KGListenMoudleLifecyleMounter appLauchWhenHomePageIsReadyDelay]