/*
 * Auto-generated by Frida. Please modify to match the signature of -[Qmeixmg qmei_ckv4r:errorCode:desc:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[Qmeixmg qmei_ckv4r:${args[2]} errorCode:${args[3]} desc:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
