/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURLSession dataTaskWithRequest:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURLSession dataTaskWithRequest:${args[2]}]`);
    let objcObj1 = ObjC.Object(args[2]);
    log('👉'+ objcObj1.toString() + '（' + objcObj1.$className + '）');
    //调用栈
    // log('stack: '+ Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
  },

  onLeave(log, retval, state) {
    let objcObj = ObjC.Object(retval);
    log('👈: '+ objcObj.$className +" "+ objcObj.toString() + '\n');
  }
});