/*
 * Auto-generated by Frida. Please modify to match the signature of -[TDeviceInfoUtil GetQIMEI:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[TDeviceInfoUtil GetQIMEI:${args[2]}]`);
  },

  onLeave(log, retval, state) {
    const ret = ObjC.Object(retval);
    log(`-[TDeviceInfoUtil GetQIMEI:] ret=${ret.toString()}`);
  }
});
