/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol getAppointPlayViewThemeWithRecordRackId:inH5View:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol getAppointPlayViewThemeWithRecordRackId:${args[2]} inH5View:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
