/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setCCInteractStateOff:withKey:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setCCInteractStateOff:${args[2]} withKey:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
