/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setIsUsingRecommendSortInMineMusic:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setIsUsingRecommendSortInMineMusic:${args[2]}]`);
  },

  onLeave(log, retval, state) {
  }
});
