/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setLastPrivateFmNeedSyncTime:withRetryNum:withUserId:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setLastPrivateFmNeedSyncTime:${args[2]} withRetryNum:${args[3]} withUserId:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
