/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setListenRankListNumberWithNumber:andUserID:andListType:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setListenRankListNumberWithNumber:${args[2]} andUserID:${args[3]} andListType:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
