/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setManageMikeSwitchWithUserId:groupId:isOn:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setManageMikeSwitchWithUserId:${args[2]} groupId:${args[3]} isOn:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
