/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setMyCollectSongMaxCount:withIsMyFavor:withUserID:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setMyCollectSongMaxCount:${args[2]} withIsMyFavor:${args[3]} withUserID:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
