/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setRankGender:ofRankId:tagId:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setRankGender:${args[2]} ofRankId:${args[3]} tagId:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
