/*
 * Auto-generated by Frida. Please modify to match the signature of +[ConfigProtocol setSoundReadExpriVipTipsCacheWithTipString:timeString:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[ConfigProtocol setSoundReadExpriVipTipsCacheWithTipString:${args[2]} timeString:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
