/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSJSONSerialization dataWithJSONObjectSafe:options:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSJSONSerialization dataWithJSONObjectSafe:${args[2]} options:${args[3]} error:${args[4]}]`);
    log("👉 JSON -> NSData 入参:" + ObjC.Object(args[2]));
    // log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    log('------------------------------------------------------------------------------------------------');
  },

  onLeave(log, retval, state) {
  }
});
