/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSJSONSerialization dataWithJSONObject:options:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */
//使用方法 frida-trace -U -f com.kugou.kugou1002 -m "+[NSJSONSerialization dataWithJSONObject:options:error:]"

defineHandler({
  onEnter(log, args, state) {
    // log(`+[NSJSONSerialization dataWithJSONObject:${args[2]} options:${args[3]} error:${args[4]}]`);
    // log("👉 JSON -> NSData 入参:" + ObjC.Object(args[2]));

    const dic = ObjC.Object(args[2]);
    log(dic.$className);
    const key = ObjC.classes.NSString.stringWithString_("dev");
    if (dic.objectForKey_(key) !== null) {
      log("👉 JSON -> NSData 入参" + dic);
      log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    }
  },

  onLeave(log, retval, state) {
  }
});
