/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSJSONSerialization JSONObjectWithData:options:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

//frida-trace -U -f com.kugou.kugou1002 -m "+[NSJSONSerialization JSONObjectWithData:options:error:]" -o resp.json

defineHandler({
  onEnter(log, args, state) {
    // log(`+[NSJSONSerialization JSONObjectWithData:${args[2]} options:${args[3]} error:${args[4]}]`);
    // this.args2 = args[2];
    // log("👉 NSData -> JSON 出参:" + ObjC.Object(args[2]));
    // log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    // log('------------------------------------------------------------------------------------------------');
  },

  onLeave(log, retval, state) {
    const dic = ObjC.Object(retval);
    // log("👉  ->" + dic + dic.$className);
    // log("👉  ->" + dic.allKeys());
    // // 仅当字典包含 key "q36" 时进入
    const key = ObjC.classes.NSString.stringWithString_("q36");

    // log("👉 allkeys:" + allkeys);
    if (dic.objectForKey_(key) !== null) {
      log("👉 NSData -> JSON 出参:" + dic);
      log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n'));
    }
  }
});