/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString dataUsingEncoding:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

// frida-trace -D fa6f4e5a190858ab2441952057f189eb5c15b595 -f com.kugou.kugou1002 -m "-[NSString dataUsingEncoding:]"

// __handlers__/__NSString_dataUsingEncoding_.js
defineHandler({
  onEnter(log, args, state) {
    // args[0] 是 NSString 对象 (self)
    // args[1] 是 selector (dataUsingEncoding:)
    // args[2] 是编码参数
    
    var stringObject = new ObjC.Object(args[0]);
    var encoding = args[2];
    
    var stringContent = stringObject.toString();
    // 如果是 IDFA 相关，打印更多信息
    if (stringContent && stringContent.includes('fae0c6104adffedfd37614e500001de19917')) {
      log('-[NSString dataUsingEncoding:]' + stringContent);
      log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
    }
    // log('-[NSString dataUsingEncoding:] 被调用');
    // log('字符串内容:1 ' + stringContent);
    // log('编码: ' + encoding);
    // log('字符串长度: ' + stringContent.length);
    
    // 保存到状态中，供 onLeave 使用
    state.stringContent = stringContent;
  },

  onLeave(log, retval, state) {
    var nsData = new ObjC.Object(retval);
  }
});

/**
 
  2317 ms  -[NSString dataUsingEncoding:]{"o16":"11ca09173e0e2c6121e2f5a55354fa88888","o36":"fae0c6104adffedfd37614e500001de19917"}
  2317 ms  0x102228c48 kugou!+[NSDictionary dictionaryWithJSONString:error:]
0x1002f86a0 kugou!-[KGTencentStatistics setUpOStar]
0x1002f83c4 kugou!-[KGTencentStatistics setUpTencentStatics]
0x1002f6588 kugou!0x4e588 (0x10004e588)
0x1ca6027c8 libdispatch.dylib!_dispatch_client_callout
0x1ca5d2f40 libdispatch.dylib!_dispatch_once_callout
0x1002f6510 kugou!+[KGAutoTrackTask setupStatics]
0x108fc1ec0 kugou!-[KGStartUpTaskManager pTaskObjectperform:queueKey:]
0x108fc0d00 kugou!0x8d18d00 (0x108d18d00)
0x108fbf698 kugou!-[KGStartUpTaskSysQueue runTasks:]
0x108fc1bd8 kugou!-[KGStartUpTaskManager pRunQueueWithTasks:queueKey:]
0x108fc037c kugou!-[KGStartUpTaskManager pRunWithQueueKey:]
0x1005e158c kugou!0x33958c (0x10033958c)
0x107d8da30 kugou!-[KGPrivacyPolicySheetViewManager showPrivacyPolicyLaunchFromBasicMode:withOkBlock:]
0x1005e14d4 kugou!0x3394d4 (0x1003394d4)
0x1005dff60 kugou!-[SceneDelegate scene:willConnectToSession:options:]

  4858 ms  -[NSString dataUsingEncoding:]{"o16":"11ca09173e0e2c6121e2f5a55354fa88888","o36":"fae0c6104adffedfd37614e500001de19917"}
  4858 ms  0x102228c48 kugou!+[NSDictionary dictionaryWithJSONString:error:]
0x1002f8f88 kugou!-[KGTencentStatistics getQimei]
0x1002f83d4 kugou!-[KGTencentStatistics setUpTencentStatics]
0x1002f6588 kugou!0x4e588 (0x10004e588)
0x1ca6027c8 libdispatch.dylib!_dispatch_client_callout
0x1ca5d2f40 libdispatch.dylib!_dispatch_once_callout
0x1002f6510 kugou!+[KGAutoTrackTask setupStatics]
0x108fc1ec0 kugou!-[KGStartUpTaskManager pTaskObjectperform:queueKey:]
0x108fc0d00 kugou!0x8d18d00 (0x108d18d00)
0x108fbf698 kugou!-[KGStartUpTaskSysQueue runTasks:]
0x108fc1bd8 kugou!-[KGStartUpTaskManager pRunQueueWithTasks:queueKey:]
0x108fc037c kugou!-[KGStartUpTaskManager pRunWithQueueKey:]
0x1005e158c kugou!0x33958c (0x10033958c)
0x107d8da30 kugou!-[KGPrivacyPolicySheetViewManager showPrivacyPolicyLaunchFromBasicMode:withOkBlock:]
0x1005e14d4 kugou!0x3394d4 (0x1003394d4)
0x1005dff60 kugou!-[SceneDelegate scene:willConnectToSession:options:]

  5514 ms  -[NSString dataUsingEncoding:]{"o16":"11ca09173e0e2c6121e2f5a55354fa88888","o36":"fae0c6104adffedfd37614e500001de19917"}
  5514 ms  0x1179e4a34 KGThirdParty!-[NSString(YYAdd) jsonValueDecoded]
0x100372318 kugou!0xca318 (0x1000ca318)
0x11a5e2e6c HookKuGou.dylib!hook_KGTencentStatistics_q36
0x100372244 kugou!+[KGAdvertManager setupGDTTangramDeviceInfo]
0x10a3be224 kugou!-[SplashBLL splashPrepareWithLaunchType:]
0x1062d6e8c kugou!-[KGListenMoudleLifecyleMounter appLauchMakeTaskNotBeforeDataUpdate:]
0x10036fd54 kugou!-[KGListenMoudleLifecyleMounter kgEscapeDBUpgrade]
0x10036fcf4 kugou!0xc7cf4 (0x1000c7cf4)
0x104880bac kugou!0x45d8bac (0x1045d8bac)
0x1be8dbf20 CoreFoundation!__NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
0x1be95cd3c CoreFoundation!-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]
0x104880b44 kugou!-[KGAppModuleLifeCycle kgEnumerateModulesUsingBlock:]
0x10036fcb8 kugou!-[KGAppModuleLifeCycle kgEscapeDBUpgrade]
0x10570f6b0 kugou!0x54676b0 (0x1054676b0)
0x1057f0054 kugou!-[KGDataUpgradeManager upgradeDathWithBeforeUpgradeBlock:andAfterUpgradeBlock:andEscapeUpgradeBlock:]
0x10570f5f8 kugou!-[KGCommonMoudleDBUpgradeMounter application:didFinishLaunchingWithOptions:]

  7699 ms  -[NSString dataUsingEncoding:]{"q16":"11ca09173e0e2c6121e2f5a55354fa88888","q36":"fae0c6104adffedfd37614e500001de19917"}
  7699 ms  0x100364b00 kugou!-[QimeiContent initWithQimeiJson:]
0x100347aa0 kugou!-[Qmeiegtm qmei_qrlegk:serverCode:]
0x10034755c kugou!-[Qmeiegtm qmei_e948ze8:code:]
0x100361b38 kugou!0xb9b38 (0x1000b9b38)
0x10cfb45c0 kugou!0xcd0c5c0 (0x10cd0c5c0)
0x10032aa70 kugou!0x82a70 (0x100082a70)
0x10032a2e4 kugou!0x822e4 (0x1000822e4)
0x109152734 kugou!0x8eaa734 (0x108eaa734)
0x1ca601850 libdispatch.dylib!_dispatch_call_block_and_release
0x1ca6027c8 libdispatch.dylib!_dispatch_client_callout
0x1ca5e3f18 libdispatch.dylib!_dispatch_main_queue_drain
0x1ca5e3b90 libdispatch.dylib!_dispatch_main_queue_callback_4CF$VARIANT$armv81
0x1be965848 CoreFoundation!__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
0x1be9494d4 CoreFoundation!__CFRunLoopRun
0x1be94db7c CoreFoundation!CFRunLoopRunSpecific
0x1f8cd9984 GraphicsServices!GSEventRunModal

  9941 ms  -[NSString dataUsingEncoding:]{"o16":"11ca09173e0e2c6121e2f5a55354fa88888","o36":"fae0c6104adffedfd37614e500001de19917"}
  9941 ms  0x11a5e4958 HookKuGou.dylib!hook_NSUserDefaults_setObject_forKey
0x109152974 kugou!-[KGTencentStatistics setTencentAutoTrackSeverGenUdidBigNumber:]
0x1091528a8 kugou!-[KGTencentStatistics forceRereshDeviceIDMachineName:o36:]
0x1091527b0 kugou!-[KGTencentStatistics update:o36:]
0x10036c864 kugou!-[OstarService updateO16:o36:]
0x100345b08 kugou!-[Qmeiegtm qmei_evkj6p0:]
0x100347af0 kugou!-[Qmeiegtm qmei_qrlegk:serverCode:]
0x10034755c kugou!-[Qmeiegtm qmei_e948ze8:code:]
0x100361b38 kugou!0xb9b38 (0x1000b9b38)
0x10cfb45c0 kugou!0xcd0c5c0 (0x10cd0c5c0)
0x10032aa70 kugou!0x82a70 (0x100082a70)
0x10032a2e4 kugou!0x822e4 (0x1000822e4)
0x109152734 kugou!0x8eaa734 (0x108eaa734)
0x1ca601850 libdispatch.dylib!_dispatch_call_block_and_release
0x1ca6027c8 libdispatch.dylib!_dispatch_client_callout
0x1ca5e3f18 libdispatch.dylib!_dispatch_main_queue_drain

 10469 ms  -[NSString dataUsingEncoding:]{"o16":"11ca09173e0e2c6121e2f5a55354fa88888","o36":"fae0c6104adffedfd37614e500001de19917"}
 10469 ms  0x117a06198 KGThirdParty!+[UICKeyChainStore setString:forKey:service:accessGroup:]
0x117a0610c KGThirdParty!+[UICKeyChainStore setString:forKey:]
0x1091528c0 kugou!-[KGTencentStatistics forceRereshDeviceIDMachineName:o36:]
0x1091527b0 kugou!-[KGTencentStatistics update:o36:]
0x10036c864 kugou!-[OstarService updateO16:o36:]
0x100345b08 kugou!-[Qmeiegtm qmei_evkj6p0:]
0x100347af0 kugou!-[Qmeiegtm qmei_qrlegk:serverCode:]
0x10034755c kugou!-[Qmeiegtm qmei_e948ze8:code:]
0x100361b38 kugou!0xb9b38 (0x1000b9b38)
0x10cfb45c0 kugou!0xcd0c5c0 (0x10cd0c5c0)
0x10032aa70 kugou!0x82a70 (0x100082a70)
0x10032a2e4 kugou!0x822e4 (0x1000822e4)
0x109152734 kugou!0x8eaa734 (0x108eaa734)
0x1ca601850 libdispatch.dylib!_dispatch_call_block_and_release
0x1ca6027c8 libdispatch.dylib!_dispatch_client_callout
0x1ca5e3f18 libdispatch.dylib!_dispatch_main_queue_drain



 13478 ms  -[NSString dataUsingEncoding:]{"q16":"fae0c6104adffedfd37614e500001de19917","q36":"fae0c6104adffedfd37614e500001de19917"}
 13478 ms  0x11a5e5cf4 HookKuGou.dylib!hook_TDMQimeiBundleUtil_getPasswordForUsername_andServiceName_accAttribute_error_
0x10d1dfad0 kugou!+[TDMQimeiBundleUtil getQimeiJsonWithAppkey:error:]
0x10d1e2404 kugou!-[TDMQimeiHandler qimeiContent]
0x10d1dc9e4 kugou!-[TDMQimeiService getQimei]
0x119260644 TDataMaster!-[TDeviceInfoUtil GetQIMEI:]
0x11a5e3048 HookKuGou.dylib!hook_TDeviceInfoUtil_GetQIMEI_
0x11929bc88 TDataMaster!TDM::TDeviceInfoCollect::GetQIMEI()
0x119255f4c TDataMaster!TDM::TDeviceInfoHolder::CollectStringDeviceInfo(tdm_tp_stl_c::tdm_string const&, TDM::DeviceInfo<tdm_tp_stl_c::tdm_string>*)
0x1192561f4 TDataMaster!TDM::TDeviceInfoHolder::CollectAllDeviceInfoFromSystem()
0x1192555f4 TDataMaster!TDM::TDeviceInfoHolder::GetStringDeviceInfo(char const*, TDM::DeviceInfo<tdm_tp_stl_c::tdm_string>*)
0x119259ce4 TDataMaster!TDM::TDeviceInfoHolder::IsAsyncDeviceCollectComplete()
0x119267e94 TDataMaster!TDM::TDMEventQueue::SwapEventToReportQueue()
0x119277d74 TDataMaster!TDM::TDataMasterReporter::ProcessSingleThread(void*)
0x1192774d0 TDataMaster!TDM::TDataMasterReporter::ProcessThread(void*)
0x20b080060 libsystem_pthread.dylib!_pthread_start

*/