/*
 * Auto-generated by Frida. Please modify to match the signature of +[Qmeibgx qmei_mmkhq].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[Qmeibgx qmei_mmkhq]`);
  },

  onLeave(log, retval, state) {
    const objcObj = new ObjC.Object(retval);
    log(`👈: ${objcObj.$className + objcObj.toString()}`);
  }
});
