/*
 * Auto-generated by Frida. Please modify to match the signature of -[KGAPMDurationAdapter processAPMData:andHistoryAMPData:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[KGAPMDurationAdapter processAPMData:${args[2]} andHistoryAMPData:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
